apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/LuminyAI/documentation.git'
    targetRevision: HEAD
    path: my-website/application_manifests
    # helm:
    #   valueFiles:
    #     - my-website/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true